START TRANSACTION;

USE CERTIFICATE;

SET @ZIPCODE = '31254';

SET @RESIDENT_REGISTRATION_NUMBER = '120315-*******';

SET @DAD_RESIDENT_REGISTRATION_NUMBER = '790510-*******';

SET @MOM_RESIDENT_REGISTRATION_NUMBER = '820821-*******';

SET @NOTIFY_PERSON_RESIDENT_REGISTRATION_NUMBER = '790510-*******';

SET @NOTIFY_PERSON_NAME = '남기준';

SET @NAME = '남기석';

SET @GENDER = '남';

SET @DATE_OF_BIRTH = '2012-03-15 14:59:00';

SET @QUALIFICATION = '부';

SET @EMAIL = 'nam@nhnad.co.kr';

SET @PHONE_NUMBER = '010-1234-5678';

SET @RESIDENCE = '경기도 성남시 분당구 대왕판교로645번길';

SET @BIRTHPLACE = '병원';

# 출생신고일
SET @NOTIFY_DATETIME = '2012-03-17';

# 모 이름
SET @MOM_NAME = '이주은';

#부 이름
SET @DAD_NAME = '남기준';


# 출생자 사람 등록
INSERT INTO CERTIFICATE.PERSON (GENDER_CODE, RESIDENT_REGISTRATION_NUMBER, NAME)
VALUES ((SELECT CODE FROM GENDER_CODE WHERE NAME = @GENDER), @RESIDENT_REGISTRATION_NUMBER, @NAME);

# 신고자 등록
INSERT INTO CERTIFICATE.NOTIFY_INFO ( PERSON_ID, NOTIFY_CODE, TARGET_PERSON_ID, QUALIFICATION_CODE_ID, EMAIL
                                         , PHONE_NUMBER, CREATE_DATETIME)
VALUES ( (SELECT ID
          FROM PERSON
          WHERE NAME = @NOTIFY_PERSON_NAME
            AND RESIDENT_REGISTRATION_NUMBER =
                @NOTIFY_PERSON_RESIDENT_REGISTRATION_NUMBER)
       , (SELECT CODE FROM NOTIFY_CODE WHERE NAME = '출생신고')
       , (SELECT ID
          FROM PERSON
          WHERE NAME = @NAME
            AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT ID FROM QUALIFICATION_CODE WHERE NAME = @QUALIFICATION)
       , @EMAIL, @PHONE_NUMBER
       , @NOTIFY_DATETIME);

# 출생자의 주소 등록
INSERT INTO ADDRESS(ZIP_CODE, ADDRESS)
    (SELECT @ZIPCODE
          , @RESIDENCE
     FROM ADDRESS
     WHERE NOT EXISTS(SELECT ADDRESS FROM ADDRESS WHERE ADDRESS = @RESIDENCE));

# 출생정보 등록
INSERT INTO CERTIFICATE.BIRTH_INFO (PERSON_ID, ADDRESS_ID, GENDER_CODE, BIRTH_PLACE_CODE, BIRTH_DATETIME)
VALUES ( (SELECT ID FROM PERSON WHERE NAME = @NAME AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT ID FROM ADDRESS WHERE ADDRESS = @RESIDENCE), (SELECT PERSON.GENDER_CODE
                                                               FROM PERSON
                                                               WHERE NAME = @NAME
                                                                 AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT CODE FROM BIRTH_PLACE_CODE WHERE NAME = @BIRTHPLACE), @DATE_OF_BIRTH);

# 집 등록
INSERT INTO RESIDENCE (PERSON_ID, ADDRESS_ID, CHANGE_REASON_CODE_ID, CREATE_DATETIME)
VALUES ( (SELECT ID FROM PERSON WHERE NAME = @NAME AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT ID FROM ADDRESS WHERE ADDRESS = @RESIDENCE)
       , (SELECT ID FROM CHANGE_REASON_CODE CRC WHERE CRC.NAME = '출생등록')
       , @NOTIFY_DATETIME);

# 가족 등록
INSERT INTO FAMILY (PERSON_ID, TARGET_PERSON_ID, FAMILY_RELATION_CODE)
VALUES ( (SELECT ID FROM PERSON WHERE NAME = @NAME AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT ID
          FROM PERSON
          WHERE NAME = @DAD_NAME AND RESIDENT_REGISTRATION_NUMBER = @DAD_RESIDENT_REGISTRATION_NUMBER)
       , (SELECT CODE FROM FAMILY_RELATION_CODE FRC WHERE FRC.NAME = '자녀'))
     , ( (SELECT ID FROM PERSON WHERE NAME = @NAME AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT ID
          FROM PERSON
          WHERE NAME = @MOM_NAME AND RESIDENT_REGISTRATION_NUMBER = @MOM_RESIDENT_REGISTRATION_NUMBER)
       , (SELECT CODE FROM FAMILY_RELATION_CODE FRC WHERE FRC.NAME = '자녀'))
     , ( (SELECT ID
          FROM PERSON
          WHERE NAME = @MOM_NAME AND RESIDENT_REGISTRATION_NUMBER = @MOM_RESIDENT_REGISTRATION_NUMBER)
       , (SELECT ID FROM PERSON WHERE NAME = @NAME AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT CODE FROM FAMILY_RELATION_CODE FRC WHERE FRC.NAME = '모'))
     , ( (SELECT ID
          FROM PERSON
          WHERE NAME = @DAD_NAME AND RESIDENT_REGISTRATION_NUMBER = @DAD_RESIDENT_REGISTRATION_NUMBER)
       , (SELECT ID FROM PERSON WHERE NAME = @NAME AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT CODE FROM FAMILY_RELATION_CODE FRC WHERE FRC.NAME = '부'));

# 세대주 관계 등록
INSERT INTO CERTIFICATE.HOUSEHOLD (PERSON_ID, HOUSEHOLDER_ID, RELATION_CODE)
VALUES ( (SELECT ID FROM PERSON WHERE NAME = @NAME AND RESIDENT_REGISTRATION_NUMBER = @RESIDENT_REGISTRATION_NUMBER)
       , (SELECT P.ID
          FROM PERSON                           P
                   JOIN RESIDENCE               R
                        ON P.ID = R.PERSON_ID
                   JOIN ADDRESS                 A
                        ON A.ID = R.ADDRESS_ID
                   JOIN HOUSEHOLD               H
                        ON P.ID = H.PERSON_ID
                   JOIN HOUSEHOLD_RELATION_CODE HRC
                        ON HRC.CODE = H.RELATION_CODE
          WHERE HRC.NAME = '본인'
            AND A.ID = (SELECT A.ID
                        FROM RESIDENCE        R
                                 JOIN ADDRESS A
                                      ON A.ID = R.ADDRESS_ID
                        WHERE A.ADDRESS = @RESIDENCE
                        ORDER BY R.CREATE_DATETIME DESC
                        LIMIT 1)
          ORDER BY CREATE_DATETIME DESC
          LIMIT 1)
       , (SELECT CODE FROM HOUSEHOLD_RELATION_CODE WHERE NAME = '자녀'));

COMMIT;
